{
 "title": "CC Flink Example Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "compute_pools",
    "label": "Compute Pool(s)",
    "query": {
     "query": "label_values(confluent_flink_compute_pool_utilization_cfu_limit,compute_pool_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CFU Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Compute Pools",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (group by (compute_pool_id) (confluent_flink_compute_pool_utilization_current_cfus))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilization per Compute Pool",
   "type": "timeseries",
   "description": "% utilization per compute pool, meaning the current CFU consumption divided by the compute pool limit",
   "gridPos": { "h": 11, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "confluent_flink_compute_pool_utilization_current_cfus{compute_pool_id=~\"$compute_pools\"} / confluent_flink_compute_pool_utilization_cfu_limit{compute_pool_id=~\"$compute_pools\"}",
     "legendFormat": "{{compute_pool_id}}"
    }
   ]
  },
  {
   "title": "Total Current CFUs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(confluent_flink_compute_pool_utilization_current_cfus)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CFU Capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(confluent_flink_compute_pool_utilization_cfu_limit)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Statement Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true
  },
  {
   "title": "Number of Statements by Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(status) (confluent_flink_statement_status{compute_pool_id=~\"$compute_pools\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "List of Non-Terminal Statements",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "confluent_flink_statement_status{status!~\"COMPLETED|FAILED\", compute_pool_id=~\"$compute_pools\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Statements per Status over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "count by (status) (confluent_flink_statement_status{compute_pool_id=~\"$compute_pools\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Statement Progress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Messages Behind per Statement",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by(flink_statement_name) (confluent_flink_pending_records{compute_pool_id=~\"$compute_pools\"})",
     "legendFormat": "{{flink_statement_name}}"
    }
   ]
  }
 ]
}