apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    uid: flink-workshop-prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST
